### PR TITLE
Fixes to previous PR

### PR DESCRIPTION
**Pull request by philerooski**

### CODE REVIEW

**Review by kdaily — COMMENTED** [review]
Did the `assertr::verify` assertions get moved somewhere else?

**Comment by kdaily** [comment]
Oooh, also has conflicts to fix.

**Comment by philerooski** [comment]
> Did the `assertr::verify` assertions get moved somewhere else?

This PR is pretty old. But in the scoring package used in the current pipeline we do all the validation using functions in a separate file `validate.R`.

The idea is to output any error messages with the returned json, rather than raising an exception that immediately stops the script.

**Comment by philerooski** [comment]
Fixed conflicts 👍

**Review by kdaily — APPROVED** [review]
LG 2 me

**Pull request merged**
